name: Test Coverage

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test-coverage:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20' # Ajuste para a versão do Node.js que você usa

      - name: Install dependencies
        run: npm install

      - name: Run tests with coverage
        run: npm run test:coverage

      - name: Update README with coverage badge
        run: |
          COVERAGE=$(grep -oP '(?<=All files.*\|\s)\d+%' coverage/index.html)
          sed -i "s/\\[Coverage\\]: .*/[Coverage]: $COVERAGE/" README.md

      - name: Commit README updates
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "chore: Update coverage badge"
          git push
