name: Test Coverage

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  test-coverage:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20' # Ajuste para a versão do Node.js que você usa

      - name: Install dependencies
        run: npm install

      - name: Run tests with coverage
        run: npm run test:coverage

      - name: Configure Git
        run: |
          git config --local user.name "Renato Hideki Osaka"
          git config --local user.email "renato.osaka@hotmail.com"

      - name: Coveralls
        uses: coverallsapp/github-action@v2